include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    prefer_single_quotes: true
    # Added for accessibility and quality
    always_declare_return_types: true
    camel_case_types: true
    annotate_overrides: true
